parameters:
    devgiants.seo.seoable_trait: Devgiants\SeoBundle\Behaviour\Seoable
services:
    devgiants.seo.tools:
        class: Devgiants\SeoBundle\Service\Tools
        arguments: ['@service_container']

    # Twig Extensions
    devgiants.seo.twig_extension:
        class: Devgiants\SeoBundle\Twig\Extension\SeoExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    devgiants.seo.seoable_subscriber:
        class: Devgiants\SeoBundle\ORM\SeoableSubscriber
        public: false
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%devgiants.seo.seoable_trait%"
        tags:
            - { name: doctrine.event_subscriber }