services:
    devgiants.seo.tools:
        class: devGiants\SeoBundle\Service\Tools
        arguments: ['@service_container']

    # Twig Extensions
    devgiants.seo.twig_extension:
        class: devGiants\SeoBundle\Twig\Extension\SeoExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }